### ISSUE TITLE
Windows refuses to run outright

### ISSUE THREAD

**Issue by bytenekos** [hdlx/AltAppSwitcher#6]
![image](https://github.com/hdlx/MacAppSwitcher/assets/66184829/053bd297-8444-4571-af69-ce9d368eadc3)

Not sure what's going on here, downloaded the latest release

**Comment by hdlx** [comment]
Hi. I do sometimes have a windows defender warning, but on my side this can be bypassed easily by clicking "run anyway". It's common for unsigned windows software to be flagged as malicious.
However, I don't know why this kind of warning is trigger by some versions and not by others.
I reuploaded an exe which has this analysis: https://www.virustotal.com/gui/file/27f65c7f9038b2abfc39a9d7c4ec3a9484ec88cabc7b85b385caed7ea2f9f5eb
If this keeps happening to you, maybe you can check how to add an exception to windows defender? https://www.reddit.com/r/CrackSupport/comments/bsmupx/operation_did_not_complete/

About not being flagged as malicious, I don't think I can't do much since registering software is coslty. The source is public, this is the only strong guarantee I can give :-)

**Comment by Sukuratchi** [comment]
> The source is public, this is the only safety guarantee I can give :-)

Not saying you're distributing malware, just letting you know that this happens when trying to run it.
It would give me a defender popup before but I could just click on "run anyway", but this time it just flat out refuses to run

**Comment by hdlx** [comment]
Yes I know that's not what you meant, I was just thinking about ways to be "trusted" consistently :-) I found a Microsoft form for this kind of issue, I sent the file and a link to the repo.

**Comment by bytenekos** [comment]
Just realised this issue is still open. Closing due to it just being window's fault lol
